#!/usr/bin/env bash
# install.sh — put `s` on your PATH.
set -euo pipefail

SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
case "$SRC" in
  /[a-zA-Z]/*) SRC_NATIVE="$(printf '%s' "$SRC" | sed -E 's|^/([a-zA-Z])/|\1:/|')" ;;
  *) SRC_NATIVE="$SRC" ;;
esac

# Pick an install dir that is already on PATH, else fall back to ~/.local/bin
pick_bindir() {
  local d
  for d in "$HOME/.local/bin" "$HOME/bin" /usr/local/bin; do
    case ":$PATH:" in
      *":$d:"*) printf '%s' "$d"; return 0 ;;
    esac
  done
  printf '%s' "$HOME/.local/bin"
}

BINDIR="${1:-$(pick_bindir)}"
mkdir -p "$BINDIR"

chmod +x "$SRC/s" "$SRC"/adapters/*.sh

LINK="$BINDIR/s"
if [ -e "$LINK" ] && [ ! -L "$LINK" ]; then
  printf 'refusing to overwrite existing non-symlink: %s\n' "$LINK" >&2
  exit 1
fi
rm -f "$LINK" 2>/dev/null

# Prefer a symlink. On Windows/git-bash a symlink may silently become a
# copy (or fail), which breaks adapter discovery — so verify, and fall
# back to a tiny wrapper that execs the real script instead.
if ln -sf "$SRC/s" "$LINK" 2>/dev/null && [ -L "$LINK" ]; then
  printf '✓ linked %s → %s\n' "$LINK" "$SRC/s"
else
  rm -f "$LINK" 2>/dev/null
  {
    printf '#!/usr/bin/env bash\n'
    printf '# generated by search-router/install.sh — wrapper for %s\n' "$SRC_NATIVE/s"
    printf 'exec %q "$@"\n' "$SRC_NATIVE/s"
  } > "$LINK"
  chmod +x "$LINK"
  printf '✓ wrote wrapper %s → %s\n' "$LINK" "$SRC/s"
  printf '  (symlinks are unavailable on this filesystem)\n'
fi

case ":$PATH:" in
  *":$BINDIR:"*) ;;
  *) printf '\nnote: %s is not on your PATH. Add it:\n  export PATH="%s:$PATH"\n' \
       "$BINDIR" "$BINDIR" ;;
esac

printf '\nnext:\n  s --check          # see which adapters are available\n  s --help           # usage\n'
